apiVersion: batch/v1
kind: Job
metadata:
  name: send-mail
spec:
  template:
    spec:
      containers:
        - name: client
          image: tmaxcloudck/mail-sender-client:latest
          imagePullPolicy: Always
          env:
          - name: MAIL_SERVER
            value: http://mail-sender.default:9999/
          - name: MAIL_FROM
            value: no-reply-tc@tmax.co.kr
          - name: MAIL_SUBJECT
            value: 테스트메일
          - name: MAIL_CONTENT
            value: |
              테스트입니다
          volumeMounts:
            - name: mail-list
              mountPath: /tmp/config
      restartPolicy: Never
      volumes:
        - name: mail-list
          configMap:
            name: approver-dev
