name: mail-send
image: tmaxcloudck/mail-sender-client:v0.0.3
imagePullPolicy: Always
env:
- name: MAIL_SERVER
  value: http://mail-sender.default:9999/
- name: MAIL_FROM
  value: no-reply-tc@tmax.co.kr
- name: MAIL_SUBJECT
  value: Test CK2-2
- name: MAIL_CONTENT
  value: |
    Test Content!!!!
    WOW!!!!!!!
    HOoooou!!!!!
